version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - SECRET_KEY=jksdnfgjksabghjvbdsfjklgbvdfhsbgvhijuks
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=btpns
      - DB_USER=root
      - DB_PASSWORD=
      - DB_DRIVER=mysql
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=btpns
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
