name: CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Stop and Remove running Container
      run: docker-compose down
    - name: Remove Golang Old Image
      run: docker rmi server-travel-risk-assessment_app
    - name: Docker Compose Build
      run: docker-compose build --no-cache
    - name: Docker Compose Run
      run: docker-compose up -d
