name: CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: self-hosted

    steps:
    
    - name: Check Repo
      uses: actions/checkout@v3
    
    - name: Pulling new Git Repository
      run: sudo git pull
      
    - name: Stop and Remove running Container
      run: sudo docker-compose down
      
    - name: Remove Golang Old Image
      run: sudo docker rmi server-travel-risk-assessment_app
      
    - name: Docker Compose Build
      run: sudo docker-compose -f docker-compose-prod.yaml build --no-cache
      
    - name: Docker Compose Run
      run: sudo docker-compose -f docker-compose-prod.yaml up -d
