name: CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Go to directory
      run: cd /home/ubuntu/server-travel-risk-assessment
    - name: Stop and Remove running Container
      run: docker-compose down
    - name: Docker Compose Build
      run: docker-compose build --no-cache
    - name: Docker Compose Run
      run: docker-compose up -d
